Settings As screen:
    Fill: =RGBA(242, 242, 242, 1)
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)
    OnVisible: =

    Label1_2 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =101
        Size: =48
        Text: ="Settings"
        Width: =442
        X: =52
        Y: =96
        ZIndex: =1

    Container2_2 As groupContainer.manualLayoutContainer:
        Fill: =RGBA(255, 255, 255, 1)
        Height: =95
        RadiusBottomLeft: =9
        RadiusBottomRight: =9
        RadiusTopLeft: =9
        RadiusTopRight: =9
        Width: =568
        X: =40
        Y: =985
        ZIndex: =2

    Button1_6 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Kitchen)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Kitchen"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =84
        Y: =1000
        ZIndex: =3

    Button1_7 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Home)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Home"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =278
        Y: =1000
        ZIndex: =4

    Button1_8 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Settings)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Settings"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =474
        Y: =1000
        ZIndex: =5

    Icon1_2 As icon.Bookmark:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =34
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Bookmark
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =34
        X: =109
        Y: =1005
        ZIndex: =6

    Icon2_2 As icon.Home:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =42
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Home
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =42
        X: =299
        Y: =1000
        ZIndex: =7

    Icon3_2 As icon.Settings:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =37
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Settings
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =36
        X: =498
        Y: =1005
        ZIndex: =8

    Container5 As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.Light
        Fill: =RGBA(255, 255, 255, 1)
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        RadiusBottomLeft: =9
        RadiusBottomRight: =9
        RadiusTopLeft: =9
        RadiusTopRight: =9
        Width: =501
        X: =52
        Y: =210
        ZIndex: =9

        Label3 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Bold
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingLeft: =20
            PaddingRight: =20
            Size: =21
            Text: ="Account"
            Width: =560
            ZIndex: =1

        Label5 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Height: =50
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingLeft: =20
            PaddingRight: =20
            PaddingTop: =0
            Size: =21
            Text: |
                =If(usrjs, "John Smith",
                    If(usrjc, "John Citizen",
                        If(usrsf, "Stephen Fry")
                    )
                )
            Width: =560
            ZIndex: =2

        Label6 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingLeft: =20
            Size: =21
            Text: |-
                =If(
                    usrjs,
                    "johnsmith@email.com
                ",
                    If(
                        usrjc,
                        "johncitizen@email.com",
                        If(
                            usrsf,
                            "stephen@mail.com"
                        )
                    )
                )
            Width: =560
            ZIndex: =3

    Container6 As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.Light
        Fill: =RGBA(255, 255, 255, 1)
        Height: =505
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowY: =LayoutOverflow.Scroll
        RadiusBottomLeft: =9
        RadiusBottomRight: =9
        RadiusTopLeft: =9
        RadiusTopRight: =9
        X: =52
        Y: =447
        ZIndex: =10

        Label7 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingLeft: =20
            Size: =21
            Text: ="Allergens"
            Width: =560
            ZIndex: =1

        Checkbox1 As checkbox:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            CheckboxBorderColor: =RGBA(102, 102, 102, 1)
            CheckboxSize: =30
            CheckmarkFill: =RGBA(255, 255, 255, 1)
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =RGBA(29, 174, 255, 1)
            HoverFill: =RGBA(0, 0, 0, 0)
            LayoutMinHeight: =85
            LayoutMinWidth: =280
            PaddingLeft: =20
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =RGBA(29, 174, 255, 1)
            PressedFill: =RGBA(0, 0, 0, 0)
            Size: =21
            Text: ="Option"
            Width: =280
            ZIndex: =2

