Settings As screen:
    Fill: =RGBA(242, 242, 242, 1)
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)
    OnVisible: |-
        =Set(
            image_src,
                LookUp(user_logins, user_name = "John Smith", user_profilepic)
        )

    Label1_2 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =101
        Size: =48
        Text: ="Settings"
        Width: =442
        X: =52
        Y: =96
        ZIndex: =1

    Container2_2 As groupContainer.manualLayoutContainer:
        Fill: =RGBA(255, 255, 255, 1)
        Height: =95
        RadiusBottomLeft: =9
        RadiusBottomRight: =9
        RadiusTopLeft: =9
        RadiusTopRight: =9
        Width: =568
        X: =40
        Y: =985
        ZIndex: =2

    Button1_6 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Kitchen)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Kitchen"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =84
        Y: =1000
        ZIndex: =3

    Button1_7 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Home)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Home"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =278
        Y: =1000
        ZIndex: =4

    Button1_8 As button:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderThickness: =0
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =70
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(29, 174, 255, 1)
        HoverFill: =RGBA(255,255,255,0)
        OnSelect: =Navigate(Settings)
        PressedBorderColor: =RGBA(255,255,255,0)
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(255,255,255,0)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =12
        Text: ="Settings"
        VerticalAlign: =VerticalAlign.Bottom
        Width: =85
        X: =474
        Y: =1000
        ZIndex: =5

    Icon1_2 As icon.Bookmark:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =34
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Bookmark
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =34
        X: =109
        Y: =1005
        ZIndex: =6

    Icon2_2 As icon.Home:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =42
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Home
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =42
        X: =299
        Y: =1000
        ZIndex: =7

    Icon3_2 As icon.Settings:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =37
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Settings
        OnSelect: =Navigate(
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(0, 120, 212, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =36
        X: =498
        Y: =1005
        ZIndex: =8

    Image1 As image:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =320
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverFill: =RGBA(0, 0, 0, 0)
        Image: =
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =320
        X: =143
        Y: =183
        ZIndex: =9

    Container3 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Light
        Height: =146
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        X: =60
        Y: =205
        ZIndex: =10

        Image2 As image:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =146
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverFill: =RGBA(0, 0, 0, 0)
            Image: |
                =image_src
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =320
            ZIndex: =1

