Settings As screen:
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    Label1_2 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(29, 174, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =101
        Size: =48
        Text: ="Preferences"
        Width: =442
        X: =52
        Y: =120
        ZIndex: =1

